server:
  port: 8080
spring:
  application:
    name: LowLatencyMicroserviceApplication
  output:
    ansi:
      enabled: ALWAYS

# Spring Doc support
springdoc:
  packagesToScan: com.techienotes.lowlatencymicroservice.controller
